import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";

// ─── Types ────────────────────────────────────────────────────────────────────

export interface LoyaltyProgram {
  id: number;
  name: string;
  slug: string;
  cycle_size: number;
  rewards: Array<{ at: number; reward: string; reward_slug: string }>;
  active: boolean;
}

export interface LoyaltyProgress {
  id: number;
  customer_id: number;
  program_id: number;
  washes_in_cycle: number;
  total_washes: number;
  cycle_number: number;
  updated_at: string;
  loyalty_programs?: LoyaltyProgram;
}

export interface LoyaltyReward {
  id: number;
  customer_id: number;
  program_id: number;
  reward_name: string;
  reward_slug: string;
  status: "available" | "redeemed" | "expired";
  earned_at: string;
  expires_at: string | null;
  ticket_id: number | null;
  loyalty_programs?: LoyaltyProgram;
}

export interface LoyaltyRedemption {
  id: number;
  reward_id: number;
  customer_id: number;
  ticket_id: number | null;
  user_id: string | null;
  redeemed_at: string;
  notes: string | null;
  overridden_by_admin: boolean;
  loyalty_rewards?: LoyaltyReward;
  tickets?: { ticket_number: string } | null;
}

export interface LoyaltyWashLog {
  id: number;
  customer_id: number;
  program_id: number;
  ticket_id: number | null;
  service_id: number | null;
  wash_number: number;
  reward_earned_id: number | null;
  created_at: string;
  user_id: string | null;
  loyalty_programs?: LoyaltyProgram;
  loyalty_rewards?: LoyaltyReward | null;
  tickets?: { ticket_number: string } | null;
  services?: { name: string } | null;
}

export interface CustomerLoyaltySummary {
  progress: LoyaltyProgress[];
  rewards: LoyaltyReward[];
  washLog: LoyaltyWashLog[];
  redemptions: LoyaltyRedemption[];
}

/** A ticket item generated by a loyalty redemption (discountPercent=100, price=original) */
export interface LoyaltyTicketItem {
  serviceId: number;
  serviceName: string;
  vehicleTypeId: number;
  vehicleLabel: string;
  price: number;           // Original service price
  discountPercent: 100;    // Always 100 — net = C$0
  isLoyaltyRedemption: true;
  loyaltyRewardId: number;
  loyaltyRewardName: string;
  loyaltyOriginalPrice: number;
}

// ─── Reward block detection ───────────────────────────────────────────────────
/** Maps reward_slug → service name keywords that are blocked */
export const REWARD_BLOCK_MAP: Record<string, string[]> = {
  nitido_gratis:    ["nítido", "nitido"],
  ceramic_wax_gratis: ["ceramic wax", "ceramic"],
  breve_gratis:     ["breve"],
  pasteado_gratis:  ["pasteado"],
};

/**
 * Fixed reward → service name pattern (server authoritative, mirrored here for UX).
 * The RPC validate_loyalty_redemption enforces this server-side.
 * Pattern is matched with ILIKE %pattern% against the services catalog.
 */
export const REWARD_SERVICE_MAP: Record<string, string> = {
  nitido_gratis:      "Nítido",           // Lavado Nítido
  ceramic_wax_gratis: "Tratamiento Cerámico", // C$350 → C$0
  breve_gratis:       "Breve",            // Lavado Breve
  pasteado_gratis:    "Pasteado Meguiar's", // Pasteado Meguiar's C$65 → C$0
};

/** Returns any available reward that blocks selling the given service name */
export function findBlockingReward(
  rewards: LoyaltyReward[],
  serviceName: string
): LoyaltyReward | null {
  const lower = serviceName.toLowerCase();
  for (const reward of rewards) {
    if (reward.status !== "available") continue;
    const keywords = REWARD_BLOCK_MAP[reward.reward_slug] ?? [];
    if (keywords.some((kw) => lower.includes(kw))) return reward;
  }
  return null;
}

// ─── Hooks ───────────────────────────────────────────────────────────────────

/** All loyalty programs catalog */
export function useLoyaltyPrograms() {
  return useQuery({
    queryKey: ["loyalty_programs"],
    queryFn: async () => {
      const { data, error } = await (supabase as any)
        .from("loyalty_programs")
        .select("*")
        .eq("active", true)
        .order("id");
      if (error) throw error;
      return data as LoyaltyProgram[];
    },
  });
}

/** Full loyalty summary for one customer */
export function useCustomerLoyalty(customerId: number | null | undefined) {
  return useQuery({
    queryKey: ["customer_loyalty", customerId],
    enabled: !!customerId,
    queryFn: async () => {
      const [progressRes, rewardsRes, washLogRes, redemptionsRes] =
        await Promise.all([
          (supabase as any)
            .from("loyalty_progress")
            .select("*, loyalty_programs(*)")
            .eq("customer_id", customerId),
          (supabase as any)
            .from("loyalty_rewards")
            .select("*, loyalty_programs(*)")
            .eq("customer_id", customerId)
            .order("earned_at", { ascending: false }),
          (supabase as any)
            .from("loyalty_wash_log")
            .select(
              "*, loyalty_programs(*), loyalty_rewards(*), tickets(ticket_number), services(name)"
            )
            .eq("customer_id", customerId)
            .order("created_at", { ascending: false })
            .limit(100),
          (supabase as any)
            .from("loyalty_redemptions")
            .select("*, tickets(ticket_number), loyalty_rewards(*, loyalty_programs(*))")
            .eq("customer_id", customerId)
            .order("redeemed_at", { ascending: false }),
        ]);

      return {
        progress: (progressRes.data ?? []) as LoyaltyProgress[],
        rewards: (rewardsRes.data ?? []) as LoyaltyReward[],
        washLog: (washLogRes.data ?? []) as LoyaltyWashLog[],
        redemptions: (redemptionsRes.data ?? []) as LoyaltyRedemption[],
      } as CustomerLoyaltySummary;
    },
  });
}

/** Available rewards for a customer (status = 'available') */
export function useAvailableRewards(customerId: number | null | undefined) {
  return useQuery({
    queryKey: ["available_loyalty_rewards", customerId],
    enabled: !!customerId,
    staleTime: 0, // always fresh — critical for POS validation
    queryFn: async () => {
      const { data, error } = await (supabase as any)
        .from("loyalty_rewards")
        .select("*, loyalty_programs(*)")
        .eq("customer_id", customerId)
        .eq("status", "available");
      if (error) throw error;
      return (data ?? []) as LoyaltyReward[];
    },
  });
}

// ─── Mutations ───────────────────────────────────────────────────────────────

/** Record a wash after successful sale (calls RPC record_loyalty_v3_wash) */
export function useRecordLoyaltyV3Wash() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (params: {
      customerId: number;
      ticketId: number;
      serviceId: number;
      userId?: string;
    }) => {
      const { data, error } = await (supabase as any).rpc(
        "record_loyalty_v3_wash",
        {
          p_customer_id: params.customerId,
          p_ticket_id: params.ticketId,
          p_service_id: params.serviceId,
          p_user_id: params.userId ?? null,
        }
      );
      if (error) throw error;
      return data as {
        recorded: boolean;
        reason?: string;
        program?: string;
        program_slug?: string;
        total_washes?: number;
        washes_in_cycle?: number;
        cycle_number?: number;
        cycle_size?: number;
        rewards_earned?: Array<{
          reward_id: number;
          reward_name: string;
          reward_slug: string;
        }>;
      };
    },
    onSuccess: (_data, vars) => {
      qc.invalidateQueries({ queryKey: ["customer_loyalty", vars.customerId] });
      qc.invalidateQueries({ queryKey: ["available_loyalty_rewards", vars.customerId] });
    },
  });
}

/** Redeem a reward (calls RPC redeem_loyalty_reward) */
export function useRedeemLoyaltyReward() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (params: {
      rewardId: number;
      customerId: number;
      ticketId?: number | null;
      userId?: string;
      notes?: string;
      adminOverride?: boolean;
    }) => {
      const { data, error } = await (supabase as any).rpc(
        "redeem_loyalty_reward",
        {
          p_reward_id:       params.rewardId,
          p_ticket_id:       params.ticketId ?? null,
          p_user_id:         params.userId ?? null,
          p_notes:           params.notes ?? null,
          p_admin_override:  params.adminOverride ?? false,
        }
      );
      if (error) throw error;
      return data as { success: boolean; error?: string };
    },
    onSuccess: (_data, vars) => {
      qc.invalidateQueries({ queryKey: ["customer_loyalty", vars.customerId] });
      qc.invalidateQueries({ queryKey: ["available_loyalty_rewards", vars.customerId] });
    },
  });
}

/** Search customers for loyalty screen */
export function useSearchCustomersForLoyalty(query: string) {
  return useQuery({
    queryKey: ["loyalty_customer_search", query],
    enabled: query.trim().length >= 2,
    queryFn: async () => {
      const { data, error } = await (supabase as any)
        .from("customers")
        .select("id, name, phone, plate, is_general")
        .eq("is_general", false)
        .or(
          `name.ilike.%${query}%,phone.ilike.%${query}%,plate.ilike.%${query}%`
        )
        .order("name")
        .limit(20);
      if (error) throw error;
      return data as Array<{
        id: number;
        name: string;
        phone: string;
        plate: string;
        is_general: boolean;
      }>;
    },
  });
}

/** Server-side validation RPC before confirming payment */
export function useValidateLoyaltyRedemption() {
  return useMutation({
    mutationFn: async (params: {
      rewardId: number;
      customerId: number;
      serviceName: string;
    }) => {
      const { data, error } = await (supabase as any).rpc(
        "validate_loyalty_redemption",
        {
          p_reward_id:    params.rewardId,
          p_customer_id:  params.customerId,
          p_service_name: params.serviceName,
        }
      );
      if (error) throw error;
      return data as {
        valid: boolean;
        error?: string;
        error_msg?: string;
        expected?: string;
        received?: string;
        reward_name?: string;
        reward_slug?: string;
        service_name_like?: string;
      };
    },
  });
}
